---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flipkartsignup
spec:
  selector:
    app: flipkart
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
